services:
  wish-template:
    build:
      context: .
      args:
        - GIT_TAG=${GIT_TAG:-dev}
    image: ascii-arcade/wish-template:${GIT_TAG:-dev}
    ports:
      - "23234:23234"
    restart: always
    environment:
      - ASCII_ARCADE_LANG="EN"
    volumes:
      - ssh:/app/.ssh

volumes:
  ssh:
