services:
  knucklebones:
    build:
      context: .
      args:
        - GIT_TAG=${GIT_TAG:-dev}
    image: ascii-arcade/knucklebones:${GIT_TAG:-dev}
    ports:
      - ${PORT}:${ASCII_ARCADE_SSH_PORT:-2222}
    restart: always
    env_file:
      - .env
    environment:
      - ASCII_ARCADE_LANG="EN"
    volumes:
      - ssh:/app/.ssh

volumes:
  ssh:
